"""Tablas creadas

Revision ID: 4ba93769b4f5
Revises: 
Create Date: 2025-05-02 13:04:12.438461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba93769b4f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VENDEDOR')
    op.drop_table('FACTURACION')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FACTURACION',
    sa.Column('cae', sa.VARCHAR(length=255, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('nit_clte', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_hora_certificado', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('fecha_hora_validacion', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('id_vendedor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_vendedor'], ['VENDEDOR.id'], name='FK__FACTURACI__id_ve__5070F446'),
    sa.PrimaryKeyConstraint('cae', name='PK__FACTURAC__D83791544BA39503')
    )
    op.create_table('VENDEDOR',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__VENDEDOR__3213E83FF2DDF683')
    )
    # ### end Alembic commands ###
